title:              Data Kelps
email:              riquelmepereira60@gmail.com
description:        Esse blog servirá como meio de divulgar meus estudos na área de Ciência de Dados.
author:             Riquelme Pereira
baseurl:            ""
url:                "https://riquelmepereira.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username: riquelmeppereira
linkedin_username: Riquelme Pereira

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
